const data = {
  recipes: [
    {
      vegetarian: true,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 8,
      gaps: "no",
      preparationMinutes: null,
      cookingMinutes: null,
      aggregateLikes: 2,
      healthScore: 1,
      creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      license: "CC BY 3.0",
      sourceName: "Foodista",
      pricePerServing: 50.86,
      extendedIngredients: [
        {
          id: 20081,
          aisle: "Baking",
          image: "flour.png",
          consistency: "SOLID",
          name: "all purpose flour",
          nameClean: "wheat flour",
          original: "1 1/4 cups all purpose flour",
          originalName: "all purpose flour",
          amount: 1.25,
          unit: "cups",
          meta: [],
          measures: {
            us: { amount: 1.25, unitShort: "cups", unitLong: "cups" },
            metric: {
              amount: 156.25,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
        {
          id: 1002050,
          aisle: "Baking",
          image: "extract.png",
          consistency: "LIQUID",
          name: "almond extract",
          nameClean: "almond extract",
          original: "1 teaspoon Almond extract",
          originalName: "Almond extract",
          amount: 1.0,
          unit: "teaspoon",
          meta: [],
          measures: {
            us: { amount: 1.0, unitShort: "tsp", unitLong: "teaspoon" },
            metric: {
              amount: 1.0,
              unitShort: "tsp",
              unitLong: "teaspoon",
            },
          },
        },
        {
          id: 10112061,
          aisle: "Baking",
          image: "almonds.jpg",
          consistency: "SOLID",
          name: "almonds",
          nameClean: "sliced almonds",
          original: "1 cup sliced almonds",
          originalName: "sliced almonds",
          amount: 1.0,
          unit: "cup",
          meta: ["sliced"],
          measures: {
            us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
            metric: { amount: 92.0, unitShort: "g", unitLong: "grams" },
          },
        },
        {
          id: 19719,
          aisle: "Nut butters, Jams, and Honey",
          image: "apricot-jam.jpg",
          consistency: "SOLID",
          name: "apricot jam",
          nameClean: "apricot jam",
          original: "1/2 cup apricot jam",
          originalName: "apricot jam",
          amount: 0.5,
          unit: "cup",
          meta: [],
          measures: {
            us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
            metric: {
              amount: 118.294,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 18369,
          aisle: "Baking",
          image: "white-powder.jpg",
          consistency: "SOLID",
          name: "baking powder",
          nameClean: "baking powder",
          original: "1/4 teaspoon Baking powder",
          originalName: "Baking powder",
          amount: 0.25,
          unit: "teaspoon",
          meta: [],
          measures: {
            us: {
              amount: 0.25,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
            metric: {
              amount: 0.25,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
          },
        },
        {
          id: 1014582,
          aisle: "Oil, Vinegar, Salad Dressing",
          image: "vegetable-oil.jpg",
          consistency: "LIQUID",
          name: "canola oil",
          nameClean: "canola oil",
          original: "2/3 canola oil",
          originalName: "canola oil",
          amount: 0.6666667,
          unit: "",
          meta: [],
          measures: {
            us: { amount: 0.6666667, unitShort: "", unitLong: "" },
            metric: { amount: 0.6666667, unitShort: "", unitLong: "" },
          },
        },
        {
          id: 1123,
          aisle: "Milk, Eggs, Other Dairy",
          image: "egg.png",
          consistency: "SOLID",
          name: "egg",
          nameClean: "egg",
          original: "1 egg",
          originalName: "egg",
          amount: 1.0,
          unit: "",
          meta: [],
          measures: {
            us: { amount: 1.0, unitShort: "", unitLong: "" },
            metric: { amount: 1.0, unitShort: "", unitLong: "" },
          },
        },
        {
          id: 1123,
          aisle: "Milk, Eggs, Other Dairy",
          image: "egg.png",
          consistency: "SOLID",
          name: "eggs",
          nameClean: "egg",
          original: "4 eggs (room temperature)",
          originalName: "eggs (room temperature)",
          amount: 4.0,
          unit: "",
          meta: ["room temperature", "()"],
          measures: {
            us: { amount: 4.0, unitShort: "", unitLong: "" },
            metric: { amount: 4.0, unitShort: "", unitLong: "" },
          },
        },
        {
          id: 9152,
          aisle: "Produce",
          image: "lemon-juice.jpg",
          consistency: "LIQUID",
          name: "lemon juice",
          nameClean: "lemon juice",
          original: "1 1/2 tablespoons lemon juice",
          originalName: "lemon juice",
          amount: 1.5,
          unit: "tablespoons",
          meta: [],
          measures: {
            us: { amount: 1.5, unitShort: "Tbsps", unitLong: "Tbsps" },
            metric: {
              amount: 1.5,
              unitShort: "Tbsps",
              unitLong: "Tbsps",
            },
          },
        },
        {
          id: 9156,
          aisle: "Produce",
          image: "zest-lemon.jpg",
          consistency: "SOLID",
          name: "lemon zest",
          nameClean: "lemon peel",
          original: "2 teaspoons lemon zest",
          originalName: "lemon zest",
          amount: 2.0,
          unit: "teaspoons",
          meta: [],
          measures: {
            us: {
              amount: 2.0,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
            metric: {
              amount: 2.0,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
          },
        },
        {
          id: 1077,
          aisle: "Milk, Eggs, Other Dairy",
          image: "milk.png",
          consistency: "LIQUID",
          name: "milk",
          nameClean: "milk",
          original: "2 tablespoons milk",
          originalName: "milk",
          amount: 2.0,
          unit: "tablespoons",
          meta: [],
          measures: {
            us: { amount: 2.0, unitShort: "Tbsps", unitLong: "Tbsps" },
            metric: {
              amount: 2.0,
              unitShort: "Tbsps",
              unitLong: "Tbsps",
            },
          },
        },
        {
          id: 10414534,
          aisle: "Alcoholic Beverages",
          image: "temporary-orange-liqueur.jpg",
          consistency: "SOLID",
          name: "orange liqueur",
          nameClean: "orange liqueur",
          original: "1 tablespoon orange liqueur (optional)",
          originalName: "orange liqueur (optional)",
          amount: 1.0,
          unit: "tablespoon",
          meta: [],
          measures: {
            us: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
            metric: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
          },
        },
        {
          id: 1036,
          aisle: "Cheese",
          image: "ricotta.png",
          consistency: "SOLID",
          name: "2%% ricotta cheese",
          nameClean: "ricotta cheese",
          original: "3/4 cup 2%% ricotta cheese",
          originalName: "2%% ricotta cheese",
          amount: 0.75,
          unit: "cup",
          meta: [],
          measures: {
            us: { amount: 0.75, unitShort: "cups", unitLong: "cups" },
            metric: { amount: 186.0, unitShort: "g", unitLong: "grams" },
          },
        },
        {
          id: 11114037,
          aisle: "Alcoholic Beverages",
          image: "rum-dark.jpg",
          consistency: "LIQUID",
          name: "rum",
          nameClean: "rum",
          original: "1 1/2 teaspoons rum",
          originalName: "rum",
          amount: 1.5,
          unit: "teaspoons",
          meta: [],
          measures: {
            us: {
              amount: 1.5,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
            metric: {
              amount: 1.5,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
          },
        },
        {
          id: 2047,
          aisle: "Spices and Seasonings",
          image: "salt.jpg",
          consistency: "SOLID",
          name: "salt",
          nameClean: "table salt",
          original: "1/4 teaspoon Salt",
          originalName: "Salt",
          amount: 0.25,
          unit: "teaspoon",
          meta: [],
          measures: {
            us: {
              amount: 0.25,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
            metric: {
              amount: 0.25,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
          },
        },
        {
          id: 19335,
          aisle: "Baking",
          image: "sugar-in-bowl.png",
          consistency: "SOLID",
          name: "tablespoon sugar",
          nameClean: "sugar",
          original: "1/4 cup +2 tablespoon sugar",
          originalName: "2 tablespoon sugar",
          amount: 0.25,
          unit: "cup",
          meta: [],
          measures: {
            us: { amount: 0.25, unitShort: "cups", unitLong: "cups" },
            metric: { amount: 50.0, unitShort: "g", unitLong: "grams" },
          },
        },
        {
          id: 19335,
          aisle: "Baking",
          image: "sugar-in-bowl.png",
          consistency: "SOLID",
          name: "sugar",
          nameClean: "sugar",
          original: "cups sugar",
          originalName: "sugar",
          amount: 1.0,
          unit: "cups",
          meta: [],
          measures: {
            us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
            metric: { amount: 200.0, unitShort: "g", unitLong: "grams" },
          },
        },
        {
          id: 1052050,
          aisle: "Baking",
          image: "vanilla.jpg",
          consistency: "SOLID",
          name: "vanilla",
          nameClean: "vanilla",
          original: "1 teaspoon vanilla",
          originalName: "vanilla",
          amount: 1.0,
          unit: "teaspoon",
          meta: [],
          measures: {
            us: { amount: 1.0, unitShort: "tsp", unitLong: "teaspoon" },
            metric: {
              amount: 1.0,
              unitShort: "tsp",
              unitLong: "teaspoon",
            },
          },
        },
      ],
      id: 632176,
      title: "Almond Ricotta Cake",
      readyInMinutes: 45,
      servings: 16,
      sourceUrl: "https://www.foodista.com/recipe/JRG6RYFS/almond-ricotta-cake",
      image: "https://img.spoonacular.com/recipes/632176-556x370.jpg",
      imageType: "jpg",
      summary:
        'Need a <b>lacto ovo vegetarian dessert</b>? Almond Ricotta Cake could be a super recipe to try. This recipe serves 16. One portion of this dish contains about <b>5g of protein</b>, <b>6g of fat</b>, and a total of <b>194 calories</b>. For <b>51 cents per serving</b>, this recipe <b>covers 5%</b> of your daily requirements of vitamins and minerals. This recipe from Foodista requires 2%% ricotta cheese, egg, lemon juice, and apricot jam. 2 people have made this recipe and would make it again. From preparation to the plate, this recipe takes about <b>45 minutes</b>. Taking all factors into account, this recipe <b>earns a spoonacular score of 26%</b>, which is not so tremendous. <a href="https://spoonacular.com/recipes/ricotta-almond-cake-133194">Ricottan Almond Cake</a>, <a href="https://spoonacular.com/recipes/almond-ricotta-cake-1330335">Almond Ricotta Cake</a>, and <a href="https://spoonacular.com/recipes/lemon-almond-ricotta-cake-1186731">Lemon Almond Ricotta Cake</a> are very similar to this recipe.',
      cuisines: [],
      dishTypes: ["dessert"],
      diets: ["lacto ovo vegetarian"],
      occasions: [],
      instructions:
        "<ol><li>Cake:</li><li>In a large mixing bowl beat the eggs, sugar, and oil on high speed until thick and pale (about 8 minutes).</li><li>Add the ricotta , lemon juice,zest, rum, vanilla and almond extract. Mix until blended.</li><li>In a separate bowl, sift together the ground almonds, flour, baking powder and salt.</li><li>Whisk into the ricotta mixture, in 3 additions.</li><li>Pour the batter into 10\" springform pan which has been buttered and the bottom lined with parchment  paper.</li><li>Bake in a preheated  350F oven for 45-50.</li><li>The cake is done when a wooden skewer inserted in the center comes out clean.</li><li>Topping:</li><li>Increase your oven temperature to 375 F</li><li>Heat the milk and stir in 2 tablespoons of sugar.</li><li>Toss in the almonds, making sure that the nuts are coated.</li><li>In a separate bowl, blend together the 3/4 cup ricotta, egg, 1/4 cup sugar, zest and vanilla.</li><li>Spread the ricotta mixture topping over the baked cake and sprinkle with the almond slices.</li><li>Return to the oven and continue baking for 15 minutes, until the almonds are a golden brown.</li><li>Remove from the oven and spread the glaze over the almonds.</li><li>Allow the cake to cool before removing from the cake pan.</li><li>Glaze:</li><li>In the microwave or in a small pan heat the apricot jam until it starts to liquefy, it takes a minute or two.</li><li>Stir to make sure it doesn't burn.</li><li>Strain the jam if their is a large amount of pulp.</li><li>Brush gently on the baked cake.</li></ol>",
      analyzedInstructions: [
        {
          name: "",
          steps: [
            {
              number: 1,
              step: "Cake:In a large mixing bowl beat the eggs, sugar, and oil on high speed until thick and pale (about 8 minutes).",
              ingredients: [
                {
                  id: 19335,
                  name: "sugar",
                  localizedName: "sugar",
                  image: "sugar-in-bowl.png",
                },
                {
                  id: 1123,
                  name: "egg",
                  localizedName: "egg",
                  image: "egg.png",
                },
                {
                  id: 4582,
                  name: "cooking oil",
                  localizedName: "cooking oil",
                  image: "vegetable-oil.jpg",
                },
              ],
              equipment: [
                {
                  id: 405907,
                  name: "mixing bowl",
                  localizedName: "mixing bowl",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/mixing-bowl.jpg",
                },
              ],
              length: { number: 8, unit: "minutes" },
            },
            {
              number: 2,
              step: "Add the ricotta , lemon juice,zest, rum, vanilla and almond extract.",
              ingredients: [
                {
                  id: 1002050,
                  name: "almond extract",
                  localizedName: "almond extract",
                  image: "extract.png",
                },
                {
                  id: 9152,
                  name: "lemon juice",
                  localizedName: "lemon juice",
                  image: "lemon-juice.jpg",
                },
                {
                  id: 1036,
                  name: "ricotta cheese",
                  localizedName: "ricotta cheese",
                  image: "ricotta.png",
                },
                {
                  id: 1052050,
                  name: "vanilla",
                  localizedName: "vanilla",
                  image: "vanilla.jpg",
                },
                {
                  id: 11114037,
                  name: "rum",
                  localizedName: "rum",
                  image: "rum-dark.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 3,
              step: "Mix until blended.In a separate bowl, sift together the ground almonds, flour, baking powder and salt.",
              ingredients: [
                {
                  id: 93740,
                  name: "almond meal",
                  localizedName: "almond meal",
                  image: "almond-meal-or-almond-flour.jpg",
                },
                {
                  id: 18369,
                  name: "baking powder",
                  localizedName: "baking powder",
                  image: "white-powder.jpg",
                },
                {
                  id: 20081,
                  name: "all purpose flour",
                  localizedName: "all purpose flour",
                  image: "flour.png",
                },
                {
                  id: 2047,
                  name: "salt",
                  localizedName: "salt",
                  image: "salt.jpg",
                },
              ],
              equipment: [
                {
                  id: 404783,
                  name: "bowl",
                  localizedName: "bowl",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/bowl.jpg",
                },
              ],
            },
            {
              number: 4,
              step: "Whisk into the ricotta mixture, in 3 additions.",
              ingredients: [
                {
                  id: 1036,
                  name: "ricotta cheese",
                  localizedName: "ricotta cheese",
                  image: "ricotta.png",
                },
              ],
              equipment: [
                {
                  id: 404661,
                  name: "whisk",
                  localizedName: "whisk",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/whisk.png",
                },
              ],
            },
            {
              number: 5,
              step: 'Pour the batter into 10" springform pan which has been buttered and the bottom lined with parchment  paper.',
              ingredients: [],
              equipment: [
                {
                  id: 404650,
                  name: "springform pan",
                  localizedName: "springform pan",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/cake-pan.png",
                },
              ],
            },
            {
              number: 6,
              step: "Bake in a preheated  350F oven for 45-50.The cake is done when a wooden skewer inserted in the center comes out clean.Topping:Increase your oven temperature to 375 F",
              ingredients: [],
              equipment: [
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/oven.jpg",
                  temperature: { number: 350.0, unit: "Fahrenheit" },
                },
                {
                  id: 3065,
                  name: "skewers",
                  localizedName: "skewers",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/wooden-skewers.jpg",
                },
              ],
            },
            {
              number: 7,
              step: "Heat the milk and stir in 2 tablespoons of sugar.Toss in the almonds, making sure that the nuts are coated.In a separate bowl, blend together the 3/4 cup ricotta, egg, 1/4 cup sugar, zest and vanilla.",
              ingredients: [
                {
                  id: 12061,
                  name: "almonds",
                  localizedName: "almonds",
                  image: "almonds.jpg",
                },
                {
                  id: 1036,
                  name: "ricotta cheese",
                  localizedName: "ricotta cheese",
                  image: "ricotta.png",
                },
                {
                  id: 1052050,
                  name: "vanilla",
                  localizedName: "vanilla",
                  image: "vanilla.jpg",
                },
                {
                  id: 19335,
                  name: "sugar",
                  localizedName: "sugar",
                  image: "sugar-in-bowl.png",
                },
                {
                  id: 1077,
                  name: "milk",
                  localizedName: "milk",
                  image: "milk.png",
                },
                {
                  id: 12135,
                  name: "nuts",
                  localizedName: "nuts",
                  image: "nuts-mixed.jpg",
                },
                {
                  id: 1123,
                  name: "egg",
                  localizedName: "egg",
                  image: "egg.png",
                },
              ],
              equipment: [
                {
                  id: 404783,
                  name: "bowl",
                  localizedName: "bowl",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/bowl.jpg",
                },
              ],
            },
            {
              number: 8,
              step: "Spread the ricotta mixture topping over the baked cake and sprinkle with the almond slices.Return to the oven and continue baking for 15 minutes, until the almonds are a golden brown.",
              ingredients: [
                {
                  id: 10112061,
                  name: "sliced almonds",
                  localizedName: "sliced almonds",
                  image: "almonds.jpg",
                },
                {
                  id: 12061,
                  name: "almonds",
                  localizedName: "almonds",
                  image: "almonds.jpg",
                },
                {
                  id: 1036,
                  name: "ricotta cheese",
                  localizedName: "ricotta cheese",
                  image: "ricotta.png",
                },
                {
                  id: 0,
                  name: "spread",
                  localizedName: "spread",
                  image: "",
                },
              ],
              equipment: [
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/oven.jpg",
                },
              ],
              length: { number: 15, unit: "minutes" },
            },
            {
              number: 9,
              step: "Remove from the oven and spread the glaze over the almonds.Allow the cake to cool before removing from the cake pan.Glaze:In the microwave or in a small pan heat the apricot jam until it starts to liquefy, it takes a minute or two.Stir to make sure it doesn't burn.Strain the jam if their is a large amount of pulp.",
              ingredients: [
                {
                  id: 19719,
                  name: "apricot jam",
                  localizedName: "apricot jam",
                  image: "apricot-jam.jpg",
                },
                {
                  id: 12061,
                  name: "almonds",
                  localizedName: "almonds",
                  image: "almonds.jpg",
                },
                {
                  id: 0,
                  name: "spread",
                  localizedName: "spread",
                  image: "",
                },
                {
                  id: 0,
                  name: "glaze",
                  localizedName: "glaze",
                  image: "",
                },
                {
                  id: 19297,
                  name: "jam",
                  localizedName: "jam",
                  image: "strawberry-jam.png",
                },
              ],
              equipment: [
                {
                  id: 404762,
                  name: "microwave",
                  localizedName: "microwave",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/microwave.jpg",
                },
                {
                  id: 404747,
                  name: "cake form",
                  localizedName: "cake form",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/cake-pan.png",
                },
                {
                  id: 404784,
                  name: "oven",
                  localizedName: "oven",
                  image:
                    "https://spoonacular.com/cdn/equipment_100x100/oven.jpg",
                },
              ],
            },
            {
              number: 10,
              step: "Brush gently on the baked cake.",
              ingredients: [],
              equipment: [],
            },
          ],
        },
      ],
      originalId: null,
      spoonacularScore: 28.895166397094727,
      spoonacularSourceUrl:
        "https://spoonacular.com/almond-ricotta-cake-632176",
    },
  ],
};

export default data;
